---
- name: Create /var/www
  file:
    path: /var/www
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'

- name: Move tarball
  copy:
    src: files/rails-sample.tar.gz
    dest: /tmp
    owner: '{{ user }}'
    group: '{{ group }}'

- name: Unarchive tarball
  unarchive:
    src: tmp/rails-sample.tar.gz
    dest: /var/www
    remote_src: yes
    owner: '{{ user }}'
    group: '{{ group }}'
