- name: packer_ansible
  hosts: default
  become: True

  tasks:
    - name: Download Cloud Monitoring agent installation script
      get_url:
        url: https://dl.google.com/cloudagents/install-monitoring-agent.sh
        dest: /home/packer/install-monitoring-agent.sh

    - name: Install Cloud Monitoring agent
      command:
        cmd: bash install-monitoring-agent.sh
        chdir: /home/packer

    - name: Delete Cloud Monitoring agent installation script
      file:
        path: /home/packer/install-monitoring-agent.sh
        state: absent

    - name: Download Cloud Monitoring agent installation script
      get_url:
        url: https://dl.google.com/cloudagents/install-logging-agent.sh
        dest: /home/packer/install-logging-agent.sh

    - name: Install Cloud Logging agent
      command:
        cmd: bash install-logging-agent.sh
        chdir: /home/packer

    - name: Delete Cloud Logging agent installation script
      file:
        path: /home/packer/install-logging-agent.sh
        state: absent

    - name: Create kojoshin group
      group:
        name: kojoshin
        state: present

    - name: Create back user
      user:
        name: back
        groups: kojoshin
        state: present

    - name: Install yum packages
      yum:
        name:
          - git
          - gcc
          - bzip2
          - openssl-devel
          - libyaml-devel
          - libffi-devel
          - readline-devel
          - zlib-devel
          - gdbm-devel
          - ncurses-devel
          - mariadb-devel
        state: latest
        update_cache: yes

    - name: Clone rbenv repository
      git:
        repo: https://github.com/rbenv/rbenv.git
        dest: /home/back/.rbenv

    - name: Setup rbenv bash extension
      command:
        cmd: '{{ item }}'
        chdir: /home/back/.rbenv
      with_items:
        - src/configure
        - make -C src

    - name: Setup rbenv
      shell:
        cmd: '{{ item }}'
      with_items:
        - echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> /home/back/.bash_profile
        - echo 'eval "$(rbenv init -)"' >> /home/back/.bash_profile

    - name: Setup ruby-build
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: /home/back/.rbenv/plugins/ruby-build

    - name: Change owner of .rbenv
      file:
        path: /home/back/.rbenv
        state: directory
        recurse: yes
        owner: back
        group: kojoshin

    - name: Check rbenv
      shell:
        cmd: curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
        warn: false
      become_user: back
      become_flags: -i

    - name: Install ruby
      shell:
        cmd: rbenv install 2.7.1
      become_user: back
      become_flags: -i

    - name: Create directory
      file:
        path: /var/www
        state: directory
        owner: back
        group: kojoshin

    - name: Move rails
      command: mv /tmp/rails /var/www

    - name: Change owner of /var/www/rails
      file:
        path: /var/www/rails
        state: directory
        recurse: yes
        owner: back
        group: kojoshin

    - name: Set rbenv local
      shell:
        cmd: rbenv local 2.7.1
        chdir: /var/www/rails
      become_user: back
      become_flags: -i

    - name: Install gems
      bundler:
        state: present
        chdir: /var/www/rails
        exclude_groups:
          - development
          - test
      become_user: back
      become_flags: -i
