name: Learn Packer CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  repository_dispatch:
    types:
      - staging

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_VERSION: 0.12.25
  TF_WORKING_DIR: terraform/environments/learn-packer

jobs:
  packer:
    name: Build Image using packer
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.get_image_tag.outputs.image_tag }}

    steps:
      - name: Setup learn-packer
        uses: actions/checkout@v2

      - name: Setup rails-sample
        uses: actions/checkout@v2
        with:
          repository: xistz/rails-sample
          token: ${{ secrets.PAT }} # `GitHub_PAT` is a secret that contains your PAT
          path: rails-sample

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get Image tag
        id: get_image_tag
        run: |
          cd rails-sample
          echo "::set-output name=image_tag::$(git rev-parse --short HEAD)"
          echo "::set-env name=IMAGE_TAG::$(git rev-parse --short HEAD)"

      - name: Create tarball
        run: |
          tar --exclude=rails-sample/.docker \
              --exclude=rails-sample/.github \
              --exclude=rails-sample/Dockerfile \
              --exclude=rails-sample/docker-compose.yaml \
              -czf ansible/roles/rails/files/rails-sample.tar.gz \
              rails-sample

      - name: Build Image
        run: |
          packer build packer/example.json

  terraform:
    name: Provision infrastructure using terraform
    runs-on: ubuntu-latest
    needs:
      - packer

    steps:
      - name: Setup learn-packer
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Get image tag
        run: |
          echo "::set-env name=TF_VAR_image_tag::${{ needs.packer.outputs.image_tag }}"

      - name: Init
        run: |
          terraform init $TF_WORKING_DIR

      - name: Apply
        run: |
          terraform apply -auto-approve $TF_WORKING_DIR
