name: Learn Packer CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  repository_dispatch:
    types:
      - staging

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Setup learn-packer
        uses: actions/checkout@v2

      - name: Setup rails-sample
        uses: actions/checkout@v2
        with:
          repository: xistz/rails-sample
          token: ${{ secrets.PAT }} # `GitHub_PAT` is a secret that contains your PAT
          path: rails-sample

      - name: Check paths
        run: |
          ls

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get short SHA of kojoshin-back
        id: get_tag
        run: |
          echo "::set-env name=IMAGE_TAG::$(git rev-parse --short HEAD)"

      - name: Build Image
        run: |
          packer build packer/example.json
