name: Learn Packer CI

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  validate:
    name: Validate packer templates
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Validate
        run: |
          packer validate packer/example.json
